### PR TITLE
Inherit from Print class

### PR DESCRIPTION
**Pull request by jksemple**
Inherit from Arduino Print class.

This fixes Issue #55 (cannot do WebSerial.print(WiFi.localIP()) and possibly Issue #53 (memory leak)
It also allows WebSerial.print(millis()) which otherwise fails.
And allows WebSerial.printf(.....)

### CODE REVIEW

**Comment by ayushsharma82** [comment]
This is such a good solution and I kind of feel dumb on why I didn't think of it before! haha. Kudos for sharing it with everyone :)

I'll test this soon and merge it.

**Comment by ayushsharma82** [comment]
@jksemple , There is a minor incompatibility in examples with ESP32 platform. Can you please fix it?, other than that it looks very promising.

Reference: [here](https://github.com/ayushsharma82/WebSerial/actions/runs/4076612347/jobs/7191394488#step:7:154)

**Comment by jksemple** [comment]
Fixed - my apologies for a dumb error!

**Comment by asjdf** [comment]
Great PR, but I thought `WebSerial.printf("Free heap=[%u]\n", ESP.getFreeHeap());` should use `%u` instead of `%lu`.

**Comment by jksemple** [comment]
Odd that both millis() and getFreeHeap() apparently return uint32_t but millis() needs %ul and getFreeHeap() needs %u. I must be missing something. I have fixed the examples anyway.

**Comment by jksemple** [comment]
Um... So what now?

**Comment by ayushsharma82** [comment]
Sorry, I had to devote some time to my office work. I’ll test this by Thursday.

**Comment by ayushsharma82** [comment]
Tested and merged :) Brilliant solution.

**Comment by jksemple** [comment]
The joy of Open Source :-)

**Pull request merged**
